In [1]:
import pandas as pd
import csv
import pandas_gbq
import time
from datetime import datetime
import os
from google.oauth2 import service_account
from google.cloud import bigquery
from datetime import datetime
from dateutil.relativedelta import relativedelta
import numpy as np

In [2]:
CREDS = '../../converge-database-0331482f2ee5.json'
client = bigquery.Client.from_service_account_json(json_credentials_path=CREDS)

In [3]:
combined = pd.DataFrame()
set_month = "202601"

In [30]:
combined = pd.read_excel('I:New Structure/Actuarial New/Database/Farmers/'+set_month+'/01 26 Converge FIA Revised.xlsx', sheet_name='Combined GL')

In [31]:
combined.columns = combined.columns.map(str.lower)
combined.columns = combined.columns.map(lambda x : x.replace(" " , "_"))

In [32]:
combined

,journal_entry,series,trx_date,account_number,account_description,debit_amount,credit_amount,net,description,reference,...,converge_debit,converge_credit,converge_net,policy_plan,code,issue_date,ceding_allowance,unnamed:_20,unnamed:_21,unnamed:_22
0,7368,Purchasing,2026-01-05,1-C00-5100-102,Surrender Benefits Paid-FIA,1991.83,0.00,1991.83,Annuity Partial Surrender,Annuity Partial Surrender,...,1792.647,0.000,1792.647,AV7Q0R,HFIA07.0,2024-11-21,0.00000,NaN,HFIA05.0,0.0275
1,7416,Purchasing,2026-01-07,1-C00-5100-102,Surrender Benefits Paid-FIA,5178.24,0.00,5178.24,Annuity Partial Surrender,Annuity Partial Surrender,...,4660.416,0.000,4660.416,AF1Q1R,HFIA10.2,2023-12-07,0.00000,NaN,HFIA05.1,0.0275
2,7417,Purchasing,2026-01-07,1-C00-5100-102,Surrender Benefits Paid-FIA,2414.83,0.00,2414.83,Annuity Partial Surrender,Annuity Partial Surrender,...,2173.347,0.000,2173.347,AF1N2R,HFIA10.2,2024-03-21,0.00000,NaN,HFIA07.0,0.0275
3,7466,Purchasing,2026-01-09,1-C00-5100-102,Surrender Benefits Paid-FIA,693.76,0.00,693.76,Annuity RMD,Annuity RMD,...,624.384,0.000,624.384,AV1Q2R,HFIA10.2,2024-06-28,0.00000,NaN,HFIA07.1,0.0275
4,7489,Purchasing,2026-01-13,1-C00-5100-102,Surrender Benefits Paid-FIA,1160.37,0.00,1160.37,Annuity Partial Surrender,Annuity Partial Surrender,...,1044.333,0.000,1044.333,AV1Q1R,HFIA10.2,2024-09-28,0.00000,NaN,HFIA07.2,0.0275
5,7492,Purchasing,2026-01-13,1-C00-5100-102,Surrender Benefits Paid-FIA,15000.00,0.00,15000.00,Annuity Partial Surrender,Annuity Partial Surrender,...,13500.000,0.000,13500.000,AV1Q1R,HFIA10.2,2025-01-07,0.00000,NaN,HFIA10.0,0.0275
6,7530,Purchasing,2026-01-14,1-C00-5100-102,Surrender Benefits Paid-FIA,4125.85,0.00,4125.85,Annuity Partial Surrender,Annuity Partial Surrender,...,3713.265,0.000,3713.265,AF1Q1R,HFIA10.2,2023-12-07,0.00000,NaN,HFIA10.1,0.0275
7,7531,Purchasing,2026-01-14,1-C00-5100-102,Surrender Benefits Paid-FIA,10400.00,0.00,10400.00,Annuity Partial Surrender,Annuity Partial Surrender,...,9360.000,0.000,9360.000,AF1N1R,HFIA10.2,2023-12-07,0.00000,NaN,HFIA10.2,0.0275
8,7533,Purchasing,2026-01-14,1-C00-5100-102,Surrender Benefits Paid-FIA,3725.86,0.00,3725.86,Annuity Partial Surrender,Annuity Partial Surrender,...,3353.274,0.000,3353.274,AV1Q2R,HFIA10.2,2024-07-28,0.00000,NaN,NaN,NaN
9,7534,Purchasing,2026-01-14,1-C00-5100-102,Surrender Benefits Paid-FIA,4041.33,0.00,4041.33,Annuity Partial Surrender,Annuity Partial Surrender,...,3637.197,0.000,3637.197,AV1Q1R,HFIA10.2,2024-11-21,0.00000,NaN,NaN,NaN
10,7535,Purchasing,2026-01-14,1-C00-5100-102,Surrender Benefits Paid-FIA,3899.53,0.00,3899.53,Annuity Partial Surrender,Annuity Partial Surrender,...,3509.577,0.000,3509.577,AV7Q1R,HFIA07.2,2024-12-28,0.00000,NaN,NaN,NaN
11,7543,Purchasing,2026-01-15,1-C00-4650-102,Mkt Value Adj - FIA-Non Qual,451.64,0.00,451.64,REIMB SURRENDER & MVA FEES,REIMB SURRENDER & MVA FEES,...,406.476,0.000,406.476,AF1Q1R,HFIA10.2,2023-12-07,0.00000,NaN,NaN,NaN
12,7544,Purchasing,2026-01-15,1-C00-4650-102,Mkt Value Adj - FIA-Non Qual,728.31,0.00,728.31,REIMB SURRENDER & MVA FEES,REIMB SURRENDER & MVA FEES,...,655.479,0.000,655.479,AV1Q1R,HFIA10.2,2024-10-14,0.00000,NaN,NaN,NaN
13,7562,Purchasing,2026-01-16,1-C00-5100-102,Surrender Benefits Paid-FIA,9216.37,0.00,9216.37,Annuity RMD,Annuity RMD,...,8294.733,0.000,8294.733,AF1Q2R,HFIA10.2,2024-04-14,0.00000,NaN,NaN,NaN
14,7578,Purchasing,2026-01-19,1-C00-5100-102,Surrender Benefits Paid-FIA,3863.25,0.00,3863.25,Annuity Partial Surrender,Annuity Partial Surrender,...,3476.925,0.000,3476.925,AF1Q1R,HFIA10.2,2024-01-07,0.00000,NaN,NaN,NaN
15,7579,Purchasing,2026-01-19,1-C00-5100-102,Surrender Benefits Paid-FIA,4475.69,0.00,4475.69,Annuity Partial Surrender,Annuity Partial Surrender,...,4028.121,0.000,4028.121,AV1N2R,HFIA10.2,2024-07-14,0.00000,NaN,NaN,NaN
16,7588,Purchasing,2026-01-20,1-C00-5000-102,Death Benefits: Paid-FIA,24680.11,0.00,24680.11,Death Claim,Death Claim,...,22212.099,0.000,22212.099,AF1Q1R,HFIA10.2,2024-01-28,0.00000,NaN,NaN,NaN
17,7601,Purchasing,2026-01-20,1-C00-5000-102,Death Benefits: Paid-FIA,15764.03,0.00,15764.03,Death Claim,Death Claim,...,14187.627,0.000,14187.627,AV1N2R,HFIA10.2,2024-11-07,0.00000,NaN,NaN,NaN
18,7659,Purchasing,2026-01-22,1-C00-5100-102,Surrender Benefits Paid-FIA,31407.04,0.00,31407.04,Annuity Partial Surrender,Annuity Partial Surrender,...,28266.336,0.000,28266.336,AV1Q1R,HFIA10.2,2024-12-28,0.00000,NaN,NaN,NaN
19,7675,Purchasing,2026-01-23,1-C00-4650-102,Mkt Value Adj - FIA-Non Qual,498.71,0.00,498.71,Annuity Partial Surrender,Annuity Partial Surrender,...,448.839,0.000,448.839,AF1Q1R,HFIA10.2,2024-04-28,0.00000,NaN,NaN,NaN
20,7675,Purchasing,2026-01-23,1-C00-5100-102,Surrender Benefits Paid-FIA,15000.00,0.00,15000.00,Annuity Partial Surrender,Annuity Partial Surrender,...,13500.000,0.000,13500.000,AF1Q1R,HFIA10.2,2024-04-28,0.00000,NaN,NaN,NaN
21,7675,Purchasing,2026-01-23,1-C00-5100-102,Surrender Benefits Paid-FIA,0.00,2402.21,-2402.21,Annuity Partial Surrender,Annuity Partial Surrender,...,0.000,2161.989,-2161.989,AF1Q1R,HFIA10.2,2024-04-28,0.00000,NaN,NaN,NaN
22,7676,Purchasing,2026-01-23,1-C00-5100-102,Surrender Benefits Paid-FIA,5786.00,0.00,5786.00,Annuity Partial Surrender,Annuity Partial Surrender,...,5207.400,0.000,5207.400,AV1N1R,HFIA10.2,2024-08-21,0.00000,NaN,NaN,NaN
23,7677,Purchasing,2026-01-23,1-C00-5100-102,Surrender Benefits Paid-FIA,46376.69,0.00,46376.69,Annuity Partial Surrender,Annuity Partial Surrender,...,41739.021,0.000,41739.021,AV7Q1R,HFIA07.2,2025-01-14,0.00000,NaN,NaN,NaN
24,7681,Purchasing,2026-01-26,1-C00-5100-102,Surrender Benefits Paid-FIA,17201.25,0.00,17201.25,Annuity Partial Surrender,Annuity Partial Surrender,...,15481.125,0.000,15481.125,AV1Q1R,HFIA10.2,2024-06-14,0.00000,NaN,NaN,NaN
25,7684,Purchasing,2026-01-26,1-C00-5100-102,Surrender Benefits Paid-FIA,6951.68,0.00,6951.68,Annuity Partial Surrender,Annuity Partial Surrender,...,6256.512,0.000,6256.512,AV1N2R,HFIA10.2,2024-12-14,0.00000,NaN,NaN,NaN
26,7733,Financial,2026-01-02,1-C00-5100-102,Annuity Regular Distribution,300.00,0.00,300.00,Surrender Bens-FIA,16141F,...,270.000,0.000,270.000,AV1Q2R,HFIA10.2,2024-08-07,0.00000,NaN,NaN,NaN
27,7733,Financial,2026-01-02,1-C00-5100-102,Annuity Regular Distribution,0.00,39.89,-39.89,Surrender Bens-FIA,16141F,...,0.000,35.901,-35.901,AV1Q2R,HFIA10.2,2024-08-07,0.00000,NaN,NaN,NaN
28,7733,Financial,2026-01-02,1-C00-4650-102,Annuity Regular Distribution,8.78,0.00,8.78,Mkt Val Adj-FIA-NQ,16141F,...,7.902,0.000,7.902,AV1Q2R,HFIA10.2,2024-08-07,0.00000,NaN,NaN,NaN
29,7733,Financial,2026-01-06,1-C00-5100-102,Annuity Regular Distribution,750.00,0.00,750.00,Surrender Bens-FIA,18458F,...,675.000,0.000,675.000,AV1Q1R,HFIA10.2,2024-12-21,0.00000,NaN,NaN,NaN
30,7733,Financial,2026-01-06,1-C00-6000-102,Commissions,803.76,0.00,803.76,Comm Exp-FIA,19885F,...,723.384,0.000,723.384,AV1Q1R,HFIA10.2,2025-02-07,0.00000,NaN,NaN,NaN
31,7733,Financial,2026-01-06,1-C00-6000-102,Commissions,348.30,0.00,348.30,Comm Exp-FIA,19885F,...,313.470,0.000,313.470,AV1Q1R,HFIA10.2,2025-02-07,0.00000,NaN,NaN,NaN
32,7733,Financial,2026-01-06,1-C00-4001-102,Premium Income,0.00,10716.80,-10716.80,Annuity Prems-FIA-Qual,19885F,...,0.000,9645.120,-9645.120,AV1Q1R,HFIA10.2,2025-02-07,265.24080,NaN,NaN,NaN
33,7733,Financial,2026-01-08,1-C00-5100-102,Annuity Full Surrender,227796.28,0.00,227796.28,Surrender Bens-FIA,15264F,...,205016.652,0.000,205016.652,AV1N1R,HFIA10.2,2024-07-14,0.00000,NaN,NaN,NaN
34,7733,Financial,2026-01-08,1-C00-5100-102,Annuity Full Surrender,0.00,33234.82,-33234.82,Surrender Bens-FIA,15264F,...,0.000,29911.338,-29911.338,AV1N1R,HFIA10.2,2024-07-14,0.00000,NaN,NaN,NaN
35,7733,Financial,2026-01-08,1-C00-4650-102,Annuity Full Surrender,7324.20,0.00,7324.20,Mkt Val Adj-FIA-NQ,15264F,...,6591.780,0.000,6591.780,AV1N1R,HFIA10.2,2024-07-14,0.00000,NaN,NaN,NaN
36,7733,Financial,2026-01-09,1-C00-5100-102,Annuity Regular Distribution,508.00,0.00,508.00,Surrender Bens-FIA,16312F,...,457.200,0.000,457.200,AV1Q1R,HFIA10.2,2024-09-14,0.00000,NaN,NaN,NaN
37,7733,Financial,2026-01-12,1-C00-5100-102,Annuity Regular Distribution,600.00,0.00,600.00,Surrender Bens-FIA,16704F,...,540.000,0.000,540.000,AV7Q2R,HFIA07.2,2024-08-28,0.00000,NaN,NaN,NaN
38,7733,Financial,2026-01-12,1-C00-5100-102,Annuity Regular Distribution,0.00,71.15,-71.15,Surrender Bens-FIA,16704F,...,0.000,64.035,-64.035,AV7Q2R,HFIA07.2,2024-08-28,0.00000,NaN,NaN,NaN
39,7733,Financial,2026-01-12,1-C00-4650-102,Annuity Regular Distribution,2.27,0.00,2.27,Mkt Val Adj-FIA-NQ,16704F,...,2.043,0.000,2.043,AV7Q2R,HFIA07.2,2024-08-28,0.00000,NaN,NaN,NaN
40,7733,Financial,2026-01-13,1-C00-5100-102,Annuity Partial Surrender,22222.22,0.00,22222.22,Surrender Bens-FIA,18728F,...,19999.998,0.000,19999.998,AV1Q1R,HFIA10.2,2024-12-07,0.00000,NaN,NaN,NaN
41,7733,Financial,2026-01-15,1-C00-5100-102,Annuity Regular Distribution,600.00,0.00,600.00,Surrender Bens-FIA,14225F,...,540.000,0.000,540.000,AF1Q2R,HFIA10.2,2024-04-14,0.00000,NaN,NaN,NaN
42,7733,Financial,2026-01-15,1-C00-5100-102,Annuity Regular Distribution,0.00,79.31,-79.31,Surrender Bens-FIA,14225F,...,0.000,71.379,-71.379,AF1Q2R,HFIA10.2,2024-04-14,0.00000,NaN,NaN,NaN
43,7733,Financial,2026-01-15,1-C00-4650-102,Annuity Regular Distribution,16.84,0.00,16.84,Mkt Val Adj-FIA-NQ,14225F,...,15.156,0.000,15.156,AF1Q2R,HFIA10.2,2024-04-14,0.00000,NaN,NaN,NaN
44,7733,Financial,2026-01-15,1-C00-5100-102,Annuity Regular Distribution,2500.00,0.00,2500.00,Surrender Bens-FIA,17249F,...,2250.000,0.000,2250.000,AV1Q1R,HFIA10.2,2024-10-14,0.00000,NaN,NaN,NaN
45,7733,Financial,2026-01-19,1-C00-6000-102,Commissions,841.24,0.00,841.24,Comm Exp-FIA,19885F,...,757.116,0.000,757.116,AV1Q1R,HFIA10.2,2025-02-07,0.00000,NaN,NaN,NaN
46,7733,Financial,2026-01-19,1-C00-6000-102,Commissions,364.54,0.00,364.54,Comm Exp-FIA,19885F,...,328.086,0.000,328.086,AV1Q1R,HFIA10.2,2025-02-07,0.00000,NaN,NaN,NaN
47,7733,Financial,2026-01-19,1-C00-4001-102,Premium Income,0.00,11216.48,-11216.48,Annuity Prems-FIA-Qual,19885F,...,0.000,10094.832,-10094.832,AV1Q1R,HFIA10.2,2025-02-07,277.60788,NaN,NaN,NaN
48,7733,Financial,2026-01-20,1-C00-5100-102,Annuity Partial Surrender,25683.21,0.00,25683.21,Surrender Bens-FIA,18202F,...,23114.889,0.000,23114.889,AV1N1R,HFIA10.2,2024-12-14,0.00000,NaN,NaN,NaN
49,7733,Financial,2026-01-22,1-C00-5100-102,Annuity Partial Surrender,1306.86,0.00,1306.86,Surrender Bens-FIA,12597F,...,1176.174,0.000,1176.174,AF1Q1R,HFIA10.2,2023-10-14,0.00000,NaN,NaN,NaN
50,7733,Financial,2026-01-22,1-C00-5100-102,Annuity Partial Surrender,2004.82,0.00,2004.82,Surrender Bens-FIA,15184F,...,1804.338,0.000,1804.338,AF1Q1R,HFIA10.2,2024-06-14,0.00000,NaN,NaN,NaN
51,7733,Financial,2026-01-23,1-C00-5100-102,Annuity RMD,9062.75,0.00,9062.75,Surrender Bens-FIA,17294F,...,8156.475,0.000,8156.475,AV1Q0R,HFIA10.0,2025-01-14,0.00000,NaN,NaN,NaN
52,7733,Financial,2026-01-26,1-C00-5100-102,Annuity Regular Distribution,1666.67,0.00,1666.67,Surrender Bens-FIA,14508F,...,1500.003,0.000,1500.003,AF1Q1R,HFIA10.2,2024-04-28,0.00000,NaN,NaN,NaN
53,7733,Financial,2026-01-26,1-C00-5100-102,Annuity Regular Distribution,0.00,256.77,-256.77,Surrender Bens-FIA,14508F,...,0.000,231.093,-231.093,AF1Q1R,HFIA10.2,2024-04-28,0.00000,NaN,NaN,NaN
54,7733,Financial,2026-01-26,1-C00-4650-102,Annuity Regular Distribution,58.17,0.00,58.17,Mkt Val Adj-FIA-NQ,14508F,...,52.353,0.000,52.353,AF1Q1R,HFIA10.2,2024-04-28,0.00000,NaN,NaN,NaN

In [33]:
combined.debit_amount.replace(" -   ", np.nan, inplace=True)
combined.credit_amount.replace(" -   ", np.nan, inplace=True)

In [34]:
combined = combined.astype({"trx_date" : "datetime64[ns]", "debit_amount" : "float64", "credit_amount" : "float64" ,"originating_master_id" :"str", "converge_quota_share" : "float64","net" : "float64"})

In [35]:
combined = combined.iloc[:, 0:19]

In [36]:
combined = combined.iloc[:, 0:19]
combined['set_month'] = set_month

In [37]:
distribution_types = {
    'Annuity Full Surrender': 'full_surrender',
    'Annuity Partial Surrender': 'partial_surrender',
    'Annuity RMD': 'rmd',
    'Annuity Regular Distribution': 'other'
}

In [38]:
for desc, table_name in distribution_types.items():

    df = combined[
        (combined['account_number'] == '1-C00-5100-102') &
        (combined['description'] == desc)
    ].copy()

    df.rename(columns={
        "policy_id": "policy_number",
        "converge_quota_share": "quota_share",
        "net": "av_withdrawn",
        "policy_plan": "plan"
    }, inplace=True)

    df = df[[
        "policy_number",
        "plan",
        "av_withdrawn",
        "quota_share"
    ]]
    df["set_month"] = set_month
    df.info()
    try:
        df.to_gbq(
            destination_table=f"farmers_fia.{table_name}",
            project_id="converge-database",
            if_exists="append"
        )

        print(f"✅ Uploaded {desc} ({len(df)} rows) -> farmers_fia.{table_name}")

    except Exception as e:
        print(f"❌ Failed to upload {desc}: {e}")

<class 'pandas.core.frame.DataFrame'>
Int64Index: 0 entries
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   policy_number  0 non-null      object
 1   plan           0 non-null      object
 2   av_withdrawn   0 non-null      float64
 3   quota_share    0 non-null      float64
 4   set_month      0 non-null      object
dtypes: float64(2), object(3)
memory usage: 0.0+ bytes
✅ Uploaded Annuity Full Surrender (0 rows) -> farmers_fia.full_surrender
<class 'pandas.core.frame.DataFrame'>
Int64Index: 19 entries, 0 to 25
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   policy_number  19 non-null     object
 1   plan           19 non-null     object
 2   av_withdrawn   19 non-null     float64
 3   quota_share    19 non-null     float64
 4   set_month      19 non-null     object
dtypes: float64(2), object(3)
memory usage: 912.0+ bytes

100%|██████████| 1/1 [00:00<?, ?it/s]

✅ Uploaded Annuity Partial Surrender (19 rows) -> farmers_fia.partial_surrender
<class 'pandas.core.frame.DataFrame'>
Int64Index: 2 entries, 3 to 13
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   policy_number  2 non-null      object
 1   plan           2 non-null      object
 2   av_withdrawn   2 non-null      float64
 3   quota_share    2 non-null      float64
 4   set_month      2 non-null      object
dtypes: float64(2), object(3)
memory usage: 96.0+ bytes

100%|██████████| 1/1 [00:00<?, ?it/s]

✅ Uploaded Annuity RMD (2 rows) -> farmers_fia.rmd
<class 'pandas.core.frame.DataFrame'>
Int64Index: 0 entries
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   policy_number  0 non-null      object
 1   plan           0 non-null      object
 2   av_withdrawn   0 non-null      float64
 3   quota_share    0 non-null      float64
 4   set_month      0 non-null      object
dtypes: float64(2), object(3)
memory usage: 0.0+ bytes
✅ Uploaded Annuity Regular Distribution (0 rows) -> farmers_fia.other

In [39]:
premium = combined[
    (combined['account_number'].isin([
        '1-C00-4000-102',
        '1-C00-4001-102'
    ])) &
    (combined['converge_quota_share'] > 0)
]

In [40]:
premium

,journal_entry,series,trx_date,account_number,account_description,debit_amount,credit_amount,net,description,reference,originating_master_id,policy_id,converge_quota_share,converge_debit,converge_credit,converge_net,policy_plan,code,issue_date,set_month
32,7733,Financial,2026-01-06,1-C00-4001-102,Premium Income,0.0,10716.80,-10716.80,Annuity Prems-FIA-Qual,19885F,1062601,19885F,0.9,0.0,9645.120,-9645.120,AV1Q1R,HFIA10.2,2025-02-07,202601
47,7733,Financial,2026-01-19,1-C00-4001-102,Premium Income,0.0,11216.48,-11216.48,Annuity Prems-FIA-Qual,19885F,1192601,19885F,0.9,0.0,10094.832,-10094.832,AV1Q1R,HFIA10.2,2025-02-07,202601

In [41]:
premium = premium.rename(columns = {"net" : "gross_premium", "converge_quota_share" : "quota_share", "policy_id" : "policy_number"})
premium['set_month'] = set_month

In [42]:
premium = premium[['policy_number', 'gross_premium', 'quota_share', 'set_month']]

In [43]:
premium.to_gbq("converge-database.farmers.premium",
                  if_exists='append',
                  project_id="converge-database")

100%|██████████| 1/1 [00:00<?, ?it/s]

In [44]:
death = combined[
        (combined['account_number'] == '1-C00-5000-102') &
        (combined['converge_quota_share'] > 0)
    ]

In [45]:
death

,journal_entry,series,trx_date,account_number,account_description,debit_amount,credit_amount,net,description,reference,originating_master_id,policy_id,converge_quota_share,converge_debit,converge_credit,converge_net,policy_plan,code,issue_date,set_month
16,7588,Purchasing,2026-01-20,1-C00-5000-102,Death Benefits: Paid-FIA,24680.11,0.0,24680.11,Death Claim,Death Claim,P13398F -001,13398F,0.9,22212.099,0.0,22212.099,AF1Q1R,HFIA10.2,2024-01-28,202601
17,7601,Purchasing,2026-01-20,1-C00-5000-102,Death Benefits: Paid-FIA,15764.03,0.0,15764.03,Death Claim,Death Claim,P18384F -001,18384F,0.9,14187.627,0.0,14187.627,AV1N2R,HFIA10.2,2024-11-07,202601

In [46]:
death = death.rename(columns = {"net" : "net_amount", "converge_quota_share" : "quotashare", "policy_id" : "policy_number", "issue_date" : "missuedt", "policy_plan" : "plan"})
death['set_month']=set_month

In [47]:
death = death[["policy_number", "net_amount", "missuedt", "plan", "quotashare", "set_month"]]

In [48]:
death.to_gbq("converge-database.farmers_fia.death_claims",
                  if_exists='append',
                  project_id="converge-database")

100%|██████████| 1/1 [00:00<?, ?it/s]

In [23]:
combined = combined.iloc[:, 0:16]

In [24]:
combined['set_month'] = set_month
combined = combined.rename(columns = {"net" : "diff", "converge_quota_share" : "quota_share"})

In [25]:
combined = combined.drop(['converge_quota_share', 'converge_debit', 'converge_net', 'converge_credit'], axis=1, errors="ignore")

In [26]:
combined

,journal_entry,series,trx_date,account_number,account_description,debit_amount,credit_amount,diff,description,reference,originating_master_id,policy_id,quota_share,set_month
0,7368,Purchasing,2026-01-05,1-C00-5100-102,Surrender Benefits Paid-FIA,1991.83,0.00,1991.83,Annuity Partial Surrender,Annuity Partial Surrender,P17559F -001,17559F,0.9,202601
1,7416,Purchasing,2026-01-07,1-C00-5100-102,Surrender Benefits Paid-FIA,5178.24,0.00,5178.24,Annuity Partial Surrender,Annuity Partial Surrender,P13185F -002,13185F,0.9,202601
2,7417,Purchasing,2026-01-07,1-C00-5100-102,Surrender Benefits Paid-FIA,2414.83,0.00,2414.83,Annuity Partial Surrender,Annuity Partial Surrender,P13691F -001,13691F,0.9,202601
3,7466,Purchasing,2026-01-09,1-C00-5100-102,Surrender Benefits Paid-FIA,693.76,0.00,693.76,Annuity RMD,Annuity RMD,P15710F -001,15710F,0.9,202601
4,7489,Purchasing,2026-01-13,1-C00-5100-102,Surrender Benefits Paid-FIA,1160.37,0.00,1160.37,Annuity Partial Surrender,Annuity Partial Surrender,P16870F -001,16870F,0.9,202601
5,7492,Purchasing,2026-01-13,1-C00-5100-102,Surrender Benefits Paid-FIA,15000.00,0.00,15000.00,Annuity Partial Surrender,Annuity Partial Surrender,P19478F -001,19478F,0.9,202601
6,7530,Purchasing,2026-01-14,1-C00-5100-102,Surrender Benefits Paid-FIA,4125.85,0.00,4125.85,Annuity Partial Surrender,Annuity Partial Surrender,P13094F -002,13094F,0.9,202601
7,7531,Purchasing,2026-01-14,1-C00-5100-102,Surrender Benefits Paid-FIA,10400.00,0.00,10400.00,Annuity Partial Surrender,Annuity Partial Surrender,P13096F -002,13096F,0.9,202601
8,7533,Purchasing,2026-01-14,1-C00-5100-102,Surrender Benefits Paid-FIA,3725.86,0.00,3725.86,Annuity Partial Surrender,Annuity Partial Surrender,P15845F -001,15845F,0.9,202601
9,7534,Purchasing,2026-01-14,1-C00-5100-102,Surrender Benefits Paid-FIA,4041.33,0.00,4041.33,Annuity Partial Surrender,Annuity Partial Surrender,P18731F -001,18731F,0.9,202601
10,7535,Purchasing,2026-01-14,1-C00-5100-102,Surrender Benefits Paid-FIA,3899.53,0.00,3899.53,Annuity Partial Surrender,Annuity Partial Surrender,P19443F -001,19443F,0.9,202601
11,7543,Purchasing,2026-01-15,1-C00-4650-102,Mkt Value Adj - FIA-Non Qual,451.64,0.00,451.64,REIMB SURRENDER & MVA FEES,REIMB SURRENDER & MVA FEES,P13168F -002,13168F,0.9,202601
12,7544,Purchasing,2026-01-15,1-C00-4650-102,Mkt Value Adj - FIA-Non Qual,728.31,0.00,728.31,REIMB SURRENDER & MVA FEES,REIMB SURRENDER & MVA FEES,P17249F,17249F,0.9,202601
13,7562,Purchasing,2026-01-16,1-C00-5100-102,Surrender Benefits Paid-FIA,9216.37,0.00,9216.37,Annuity RMD,Annuity RMD,P14225F -001,14225F,0.9,202601
14,7578,Purchasing,2026-01-19,1-C00-5100-102,Surrender Benefits Paid-FIA,3863.25,0.00,3863.25,Annuity Partial Surrender,Annuity Partial Surrender,P13344F -002,13344F,0.9,202601
15,7579,Purchasing,2026-01-19,1-C00-5100-102,Surrender Benefits Paid-FIA,4475.69,0.00,4475.69,Annuity Partial Surrender,Annuity Partial Surrender,P15657F -001,15657F,0.9,202601
16,7588,Purchasing,2026-01-20,1-C00-5000-102,Death Benefits: Paid-FIA,24680.11,0.00,24680.11,Death Claim,Death Claim,P13398F -001,13398F,0.9,202601
17,7601,Purchasing,2026-01-20,1-C00-5000-102,Death Benefits: Paid-FIA,15764.03,0.00,15764.03,Death Claim,Death Claim,P18384F -001,18384F,0.9,202601
18,7659,Purchasing,2026-01-22,1-C00-5100-102,Surrender Benefits Paid-FIA,31407.04,0.00,31407.04,Annuity Partial Surrender,Annuity Partial Surrender,P19202F -001,19202F,0.9,202601
19,7675,Purchasing,2026-01-23,1-C00-4650-102,Mkt Value Adj - FIA-Non Qual,498.71,0.00,498.71,Annuity Partial Surrender,Annuity Partial Surrender,P14798F -001,14798F,0.9,202601
20,7675,Purchasing,2026-01-23,1-C00-5100-102,Surrender Benefits Paid-FIA,15000.00,0.00,15000.00,Annuity Partial Surrender,Annuity Partial Surrender,P14798F -001,14798F,0.9,202601
21,7675,Purchasing,2026-01-23,1-C00-5100-102,Surrender Benefits Paid-FIA,0.00,2402.21,-2402.21,Annuity Partial Surrender,Annuity Partial Surrender,P14798F -001,14798F,0.9,202601
22,7676,Purchasing,2026-01-23,1-C00-5100-102,Surrender Benefits Paid-FIA,5786.00,0.00,5786.00,Annuity Partial Surrender,Annuity Partial Surrender,P16971F -001,16971F,0.9,202601
23,7677,Purchasing,2026-01-23,1-C00-5100-102,Surrender Benefits Paid-FIA,46376.69,0.00,46376.69,Annuity Partial Surrender,Annuity Partial Surrender,P19415F -001,19415F,0.9,202601
24,7681,Purchasing,2026-01-26,1-C00-5100-102,Surrender Benefits Paid-FIA,17201.25,0.00,17201.25,Annuity Partial Surrender,Annuity Partial Surrender,P15365F -001,15365F,0.9,202601
25,7684,Purchasing,2026-01-26,1-C00-5100-102,Surrender Benefits Paid-FIA,6951.68,0.00,6951.68,Annuity Partial Surrender,Annuity Partial Surrender,P19161F -001,19161F,0.9,202601
26,7733,Financial,2026-01-02,1-C00-5100-102,Annuity Regular Distribution,300.00,0.00,300.00,Surrender Bens-FIA,16141F,1022601,16141F,0.9,202601
27,7733,Financial,2026-01-02,1-C00-5100-102,Annuity Regular Distribution,0.00,39.89,-39.89,Surrender Bens-FIA,16141F,1022601,16141F,0.9,202601
28,7733,Financial,2026-01-02,1-C00-4650-102,Annuity Regular Distribution,8.78,0.00,8.78,Mkt Val Adj-FIA-NQ,16141F,1022601,16141F,0.9,202601
29,7733,Financial,2026-01-06,1-C00-5100-102,Annuity Regular Distribution,750.00,0.00,750.00,Surrender Bens-FIA,18458F,1062601,18458F,0.9,202601
30,7733,Financial,2026-01-06,1-C00-6000-102,Commissions,803.76,0.00,803.76,Comm Exp-FIA,19885F,1062601,19885F,0.9,202601
31,7733,Financial,2026-01-06,1-C00-6000-102,Commissions,348.30,0.00,348.30,Comm Exp-FIA,19885F,1062601,19885F,0.9,202601
32,7733,Financial,2026-01-06,1-C00-4001-102,Premium Income,0.00,10716.80,-10716.80,Annuity Prems-FIA-Qual,19885F,1062601,19885F,0.9,202601
33,7733,Financial,2026-01-08,1-C00-5100-102,Annuity Full Surrender,227796.28,0.00,227796.28,Surrender Bens-FIA,15264F,1082601,15264F,0.9,202601
34,7733,Financial,2026-01-08,1-C00-5100-102,Annuity Full Surrender,0.00,33234.82,-33234.82,Surrender Bens-FIA,15264F,1082601,15264F,0.9,202601
35,7733,Financial,2026-01-08,1-C00-4650-102,Annuity Full Surrender,7324.20,0.00,7324.20,Mkt Val Adj-FIA-NQ,15264F,1082601,15264F,0.9,202601
36,7733,Financial,2026-01-09,1-C00-5100-102,Annuity Regular Distribution,508.00,0.00,508.00,Surrender Bens-FIA,16312F,1092601,16312F,0.9,202601
37,7733,Financial,2026-01-12,1-C00-5100-102,Annuity Regular Distribution,600.00,0.00,600.00,Surrender Bens-FIA,16704F,1122601,16704F,0.9,202601
38,7733,Financial,2026-01-12,1-C00-5100-102,Annuity Regular Distribution,0.00,71.15,-71.15,Surrender Bens-FIA,16704F,1122601,16704F,0.9,202601
39,7733,Financial,2026-01-12,1-C00-4650-102,Annuity Regular Distribution,2.27,0.00,2.27,Mkt Val Adj-FIA-NQ,16704F,1122601,16704F,0.9,202601
40,7733,Financial,2026-01-13,1-C00-5100-102,Annuity Partial Surrender,22222.22,0.00,22222.22,Surrender Bens-FIA,18728F,1132601,18728F,0.9,202601
41,7733,Financial,2026-01-15,1-C00-5100-102,Annuity Regular Distribution,600.00,0.00,600.00,Surrender Bens-FIA,14225F,1152601,14225F,0.9,202601
42,7733,Financial,2026-01-15,1-C00-5100-102,Annuity Regular Distribution,0.00,79.31,-79.31,Surrender Bens-FIA,14225F,1152601,14225F,0.9,202601
43,7733,Financial,2026-01-15,1-C00-4650-102,Annuity Regular Distribution,16.84,0.00,16.84,Mkt Val Adj-FIA-NQ,14225F,1152601,14225F,0.9,202601
44,7733,Financial,2026-01-15,1-C00-5100-102,Annuity Regular Distribution,2500.00,0.00,2500.00,Surrender Bens-FIA,17249F,1152601,17249F,0.9,202601
45,7733,Financial,2026-01-19,1-C00-6000-102,Commissions,841.24,0.00,841.24,Comm Exp-FIA,19885F,1192601,19885F,0.9,202601
46,7733,Financial,2026-01-19,1-C00-6000-102,Commissions,364.54,0.00,364.54,Comm Exp-FIA,19885F,1192601,19885F,0.9,202601
47,7733,Financial,2026-01-19,1-C00-4001-102,Premium Income,0.00,11216.48,-11216.48,Annuity Prems-FIA-Qual,19885F,1192601,19885F,0.9,202601
48,7733,Financial,2026-01-20,1-C00-5100-102,Annuity Partial Surrender,25683.21,0.00,25683.21,Surrender Bens-FIA,18202F,1202601,18202F,0.9,202601
49,7733,Financial,2026-01-22,1-C00-5100-102,Annuity Partial Surrender,1306.86,0.00,1306.86,Surrender Bens-FIA,12597F,1222601,12597F,0.9,202601
50,7733,Financial,2026-01-22,1-C00-5100-102,Annuity Partial Surrender,2004.82,0.00,2004.82,Surrender Bens-FIA,15184F,1222601,15184F,0.9,202601
51,7733,Financial,2026-01-23,1-C00-5100-102,Annuity RMD,9062.75,0.00,9062.75,Surrender Bens-FIA,17294F,1232601,17294F,0.9,202601
52,7733,Financial,2026-01-26,1-C00-5100-102,Annuity Regular Distribution,1666.67,0.00,1666.67,Surrender Bens-FIA,14508F,1262601,14508F,0.9,202601
53,7733,Financial,2026-01-26,1-C00-5100-102,Annuity Regular Distribution,0.00,256.77,-256.77,Surrender Bens-FIA,14508F,1262601,14508F,0.9,202601
54,7733,Financial,2026-01-26,1-C00-4650-102,Annuity Regular Distribution,58.17,0.00,58.17,Mkt Val Adj-FIA-NQ,14508F,1262601,14508F,0.9,202601

In [27]:
combined.to_gbq("converge-database.farmers.combined_gl",
                  if_exists='append',
                  project_id="converge-database")

100%|██████████| 1/1 [00:00<?, ?it/s]

In [51]:
import sys

# Add directory containing LDTI.py
sys.path.append('../../actuarial-pipelines/reconciliations/farmers/')

# Import the function
from reconciliation import run_reconciliation

# Trigger the AVRF analysis
run_reconciliation(set_month, "farmers")

    SELECT SUM(net_amount) AS total
    FROM `farmers.death_claims`
    WHERE set_month = '202601'

{'product': 'farmers', 'fieldname': 'death_claims', 'total': 2290721.3000000003}
-----------------------------------------------

    SELECT SUM(net_amount) AS total
    FROM `farmers.cancellation`
    WHERE set_month = '202601'

{'product': 'farmers', 'fieldname': 'cancellation', 'total': None}
-----------------------------------------------

    select sum(av_withdrawn*quota_share) FROM `farmers.full_surrender` WHERE set_month = "202601"

{'product': 'farmers', 'fieldname': 'full_surrender', 'total': 199005.82650000002}
-----------------------------------------------

    select sum(gross_premium*quota_share) FROM `farmers.premium` WHERE set_month = "202601"

{'product': 'farmers', 'fieldname': 'premium', 'total': -49602.308}
-----------------------------------------------

    select sum(av_withdrawn*quota_share) FROM `farmers.partial_surrender` WHERE set_month = "202601"

{'product': 'farmers', 'fieldname': 'partial_surrender', 'total': 4649.636}
-----------------------------------------------

    select sum(av_withdrawn*quota_share) FROM `farmers.rmd` WHERE set_month = "202601"

{'product': 'farmers', 'fieldname': 'rmd', 'total': 125997.53899999999}
-----------------------------------------------

    select sum(av_withdrawn*quota_share) FROM `farmers.other` WHERE set_month = "202601"

{'product': 'farmers', 'fieldname': 'other', 'total': 23060.297}
-----------------------------------------------

    SELECT SUM(credit_amount * quota_share) AS total
    FROM `farmers.combined_gl`
    WHERE set_month = '202601'
      AND account_number = '1-C00-5100-101'
      AND description IN (
          'Annuity Regular Distribution',
          'Annuity RMD',
          'Annuity Partial Surrender',
          'Annuity Full Surrender'
      )

{'product': 'farmers', 'fieldname': 'surrender_charge', 'total': 15923.517}
-----------------------------------------------

    SELECT SUM(diff * quota_share) AS total
    FROM `farmers.combined_gl`
    WHERE set_month = '202601'
      AND account_number = '1-C00-4650-101'
      AND description IN (
          'Annuity Regular Distribution',
          'Annuity RMD',
          'Annuity Partial Surrender',
          'Annuity Full Surrender'
      )

{'product': 'farmers', 'fieldname': 'mva', 'total': 2238.3755}
-----------------------------------------------

    select (100*count(mpolicy)*0.20 +
    (select 100*count(mpolicy)*0.10 from `farmers.seriatim_new`
    WHERE set_month ='202601' and new_policy_check ='NEW' and term=3) )
    as total
    from `farmers.seriatim_new`
    WHERE set_month ='202601' and new_policy_check ='NEW' and term IN (5,7,10)

{'product': 'farmers', 'fieldname': 'expense', 'total': 0.0}
-----------------------------------------------
SELECT -SUM(diff*quota_share*CASE WHEN s.term =3 THEN 0.0075
                                    WHEN s.term =5 THEN 0.01
                                    WHEN s.term = 7 THEN 0.0075
                                    WHEN s.term =10 THEN 0.0150
                                    END) as total from `farmers.combined_gl` c
                                    LEFT JOIN `farmers.seriatim_new` s ON s.mpolicy = c.policy_id AND s.set_month = c.set_month
                                    WHERE s.set_month ='202601' AND account_number IN ("1-C00-4000-101","1-C00-4001-101") AND description IN ('Cancellation', 'Premium Income')

{'product': 'farmers', 'fieldname': 'cede', 'total': 0}
-----------------------------------------------