In [1]:
import pandas as pd
import csv
import pandas_gbq
import time
from datetime import datetime
import os
from google.oauth2 import service_account
from google.cloud import bigquery
import numpy as np

In [2]:
credentials = {
  "type": "service_account",
  "project_id": "converge-database",
  "private_key_id": "0331482f2ee50f61b29ef82500091558c357976b",
  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDDgb4rYnWQbUBw\n1cm/dhEIlt2Zwtk0yrJcfBBqi1c2EHcnLNJg0+YNPhvxqAlqoeO8iFjtMIwjLg/I\nj1GjNmUJplCHqcu9F2ohg/htmMhilyT6To0I0AHH1PDZGyqdJvXh2Bl6aLD1sAGW\nSed7kY6XsVIntHAOAniBIPmvR9vpp+2btwFV5EgIaRsLzRUsK6tGDlKEooQtR4ok\nR+GI49mXsd9r8Mg4WPGYpqFb8FKJsfew50J5rI5yUhDnpfMZW9y5KDTApx1KyIdd\n/koL/ICBcBPNYXIEQze87c4gE/T/Hd5fdfQPBjtnD7SyhskyLK0vhCjyxLZzAwUK\ngB4VSfslAgMBAAECggEAQCIe+odlbnfQVFNlR5fY9Zrb3dVDwGQfx2PxVKoZ9UPI\neoLjDl1kkYKG0yqe0CqEFPQbS8+JoP66sb2F98bftR8oOqCSE5kLOSxcAcPFNEZF\nnJDJBhOKCf4J9gZJ39yIe0oS7YtLRYUzuBPNSkVQ4+UIwLqZqZbY5e8lyQCHHOnk\nE5jCUDtKYoK7v39Ol0os1R10QWBqq0C0bvXqWls8MEG9mrFoTnSgDx9io7sb5wuM\n+HPX76SEWbO9clCDq4uXZHuprWflI7ayKpo9u702XxaPIf73WcJwHVIaG7ke8B9C\nBeePzG07vJfrSXWRKSKKqQCfaCdL3coAG6tZhXi3fwKBgQD8sR1VAu/k3S4mr4co\n29aIEPUH9DwqtIg6YDLa7HwIiwtt/pEw0otDTv0Ez1ibI83y/kq61ysJl4+qJXDL\n4q7m6/hLUXYpQQ1Ly4wKOLtfw3VWf19SmvtWYFpFAVVGJxpotja0yDg7n46Ea2QJ\nZd6VqCxp5ZUZ7uPyKqcqqiDRDwKBgQDGEPmjpLNT4zdnJiI15Z4Z5eP+U4r7uzxu\nP3qErn+XCmaC/3zup1zZJBgVROeZLJW+AEIuP74+L16F3HV3qXnGcwCyC1r1IFQS\nIqIRK7A59xiYfbc6+aK9Bx+Q+zicbnLOy4pgh35T+DYwTZp5jrWh+vC9J6YO4K6u\n4GbUghAIiwKBgG7CW28FyIzyfeYrDf1UzuX5OM3xueWmGAguXlwjSAKen7Xo3U8f\nGje4iaLwF5B40y7tU2guJAkiS7BylMxpYeyKBd1NqZNPljpgz9MzJr5E+EufrPKS\nSBSGS0rv2KbVQPgg1j3LfQp1V4ynXcPYyQWkH0OThBVH5tYg6AEFbTj1AoGAKgFx\noDYO3iyjFFovCTUwaZeq2cZIBIk6ELuftUH4x0SqZv/eNBMEivyvqtsZLxAYldoi\nLwLPywpqxoLx2rXzoJXFQP1Nhg0cJ1h2/KNCVZjE+5o14OkOjX5UQIA3Cl4WNStP\nppc1wIM0otvidgNBHCBHLCabfi5Cfc4ToOAQnG8CgYEAmP5+ZTojrF3H4T+dWPnf\nojsODO2+ulXHQ9n7kmP61Mzy3urkQZptjol8SL6z26baYKnPd5Z0YuT38awr3KQB\n7D91F8bNztHbxXeRi4blr1gTLT7NPCFqsPyyTFt3n91RdjgTFAytvrG2n4zkkzOs\npV2LKuYPRIRMPrPXu8g9VEI=\n-----END PRIVATE KEY-----\n",
  "client_email": "convergedb@converge-database.iam.gserviceaccount.com",
  "client_id": "109555696894026099324",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/convergedb%40converge-database.iam.gserviceaccount.com",
  "universe_domain": "googleapis.com"
}

In [3]:
CREDS = '../../converge-database-0331482f2ee5.json'
client = bigquery.Client.from_service_account_json(json_credentials_path=CREDS)

In [4]:
seriatim = pd.DataFrame()
set_month = '202603'
folder_dest = "I:New Structure/Actuarial New/Database/ACLICO Settlements/"+set_month+"/"

In [5]:
pmdmode_map = pd.DataFrame({'pmdmode': ['A', 'S', 'Q', 'M', 'SP', 'A']})

# Define a function for the conditions
def map_pmdmode(value):
    if value == 'A':
        return 1
    elif value == 'S':
        return 2
    elif value == 'Q':
        return 4
    elif value == 'M':
        return 9
    elif value == 'SP':
        return 'P'
    return None  # Default if no condition matches

In [7]:
seriatim = pd.read_excel(folder_dest+"03-2026 ACL Life Settlement_workbook_05.05.2026_FINAL.xlsx",dtype=str, sheet_name="CONRE Reserve")

In [8]:
annuity = pd.read_excel("I:New Structure/Actuarial New/Database/ACLICO Settlements/202603/03-2026 ACL Life Settlement_workbook_05.05.2026_FINAL.xlsx", dtype=str, sheet_name ="PNAnn CONRE")

In [8]:
seriatim.columns = seriatim.columns.map(str.lower)
seriatim.columns = seriatim.columns.map(lambda x : x.replace(" " , "_"))

In [9]:
annuity.columns = annuity.columns.map(str.lower)
annuity.columns = annuity.columns.map(lambda x : x.replace(" " , "_"))

In [10]:
seriatim.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 107365 entries, 0 to 107364
Data columns (total 75 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   pmdno             107365 non-null  object
 1   pmdtype           0 non-null       object
 2   pmdmode           107365 non-null  object
 3   pmdsts            107365 non-null  object
 4   pmdstssub         107365 non-null  object
 5   pmddebit          0 non-null       object
 6   pmdissuedt        107365 non-null  object
 7   pmdissfolo        0 non-null       object
 8   pmddtdwd          107365 non-null  object
 9   pmdprmtot         107365 non-null  object
 10  pmdpaybase        107365 non-null  object
 11  pmdplan           107365 non-null  object
 12  pmdplanver        107365 non-null  object
 13  pmdoverage        107365 non-null  object
 14  pmdacctnew        0 non-null       object
 15  pmdstsexdt        6171 non-null    object
 16  pbfactive         107365 non-null  object
 17  pbfstssub         0 non-null       object
 18  pbfseqno          107365 non-null  object
 19  pbfrplan          0 non-null       object
 20  pbfrplanvr        0 non-null       object
 21  pbfbftrid         107365 non-null  object
 22  pbfcd             107301 non-null  object
 23  pbfdtcd           103775 non-null  object
 24  pbfdt             107365 non-null  object
 25  pbfamt            107365 non-null  object
 26  wrvpbfdtcd        103775 non-null  object
 27  wrvpbfdt          107365 non-null  object
 28  pbfamtrpt         107365 non-null  object
 29  pbfprm            107365 non-null  object
 30  pbfprmannl        107365 non-null  object
 31  pbfrsvcd0         107365 non-null  object
 32  pbfrsvcd1         107365 non-null  object
 33  wrvrsvcdd         2008 non-null    object
 34  wrvcalcdt         107365 non-null  object
 35  pintype           107365 non-null  object
 36  wrvblbkgrp        0 non-null       object
 37  wrvrptcd1         101803 non-null  object
 38  wrvrptcd2         6132 non-null    object
 39  wrvprmcd          101863 non-null  object
 40  wrvyr1flag        107365 non-null  object
 41  wrverrflag        5657 non-null    object
 42  wrvpbfage         107365 non-null  object
 43  wrvpbfsex         107365 non-null  object
 44  wrvage            101863 non-null  object
 45  wrvduratn         101863 non-null  object
 46  wrvprmannn        107365 non-null  object
 47  wrvload           107365 non-null  object
 48  wrvloadntg        107365 non-null  object
 49  wrvrsvamt         107365 non-null  object
 50  wrvdsvamt         107365 non-null  object
 51  wrvtsvamt         107365 non-null  object
 52  wrvprmuneg        107365 non-null  object
 53  wrvprmdefg        107365 non-null  object
 54  wrvprmdueg        107365 non-null  object
 55  wrvprmadvg        107365 non-null  object
 56  wrvprmunen        107365 non-null  object
 57  wrvprmdefn        107365 non-null  object
 58  wrvprmduen        107365 non-null  object
 59  wrvrsvfact        107365 non-null  object
 60  wrvrsvysby        107365 non-null  object
 61  wrvnpmfact        107365 non-null  object
 62  wrvdeffact        107365 non-null  object
 63  wrvtsvfact        107365 non-null  object
 64  wrvfacbase        107365 non-null  object
 65  wrvscaleby        107365 non-null  object
 66  wrvplcycnt        107365 non-null  object
 67  wrvridrcnt        107365 non-null  object
 68  wrvprmgros        107365 non-null  object
 69  wrvrcddesc        101863 non-null  object
 70  wrvclass          107365 non-null  object
 71  wrvgrpind         107365 non-null  object
 72  total_reserve     107365 non-null  object
 73  reinsurance_flag  107365 non-null  object
 74  flag              107365 non-null  object
dtypes: object(75)
memory usage: 61.4+ MB

In [11]:
annuity.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1718 entries, 0 to 1717
Data columns (total 26 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   plan        1718 non-null   object
 1   plandesc    1718 non-null   object
 2   policyno    1718 non-null   object
 3   issuedate   1718 non-null   object
 4   premium1    1718 non-null   object
 5   interest1   1718 non-null   object
 6   total1      1718 non-null   object
 7   premium2    1718 non-null   object
 8   interest2   1718 non-null   object
 9   total2      1718 non-null   object
 10  subtotal    1718 non-null   object
 11  discount    1718 non-null   object
 12  rsvamt      1718 non-null   object
 13  errormsg    0 non-null      object
 14  rptcriteri  0 non-null      object
 15  expire0     1718 non-null   object
 16  expire1     1718 non-null   object
 17  expire2     1718 non-null   object
 18  expire3     1718 non-null   object
 19  expire4     1718 non-null   object
 20  expire5     1718 non-null   object
 21  rsvamtnd    1718 non-null   object
 22  indgrp      1718 non-null   object
 23  polno       1718 non-null   object
 24  date        1718 non-null   object
 25  reinsured   1718 non-null   object
dtypes: object(26)
memory usage: 349.1+ KB

In [12]:
annuity = annuity.astype({"rsvamtnd":"float64"})

In [13]:
seriatim.rename(columns={"pmdno" : "policyno", "pbfseqno" : "amtpolicy", "pbfrsvcd1" : "valcode", "total_reserve" : "amtreserve", "pbfprmannl" : "prmannl"}, inplace=True)

In [14]:
seriatim

,policyno,pmdtype,pmdmode,pmdsts,pmdstssub,pmddebit,pmdissuedt,pmdissfolo,pmddtdwd,pmdprmtot,...,wrvscaleby,wrvplcycnt,wrvridrcnt,wrvprmgros,wrvrcddesc,wrvclass,wrvgrpind,amtreserve,reinsurance_flag,flag
0,AA-0002837,NaN,Q,A,PRMPY,NaN,2000-05-01 00:00:00,NaN,2026-05-01 00:00:00,358.8,...,0,0,1,0,NaN,ORD,I,0,AA-0002837,Y
1,AA-0003018,NaN,M,A,PRMPY,NaN,2000-06-01 00:00:00,NaN,2026-04-01 00:00:00,245.76,...,0,0,1,0,NaN,ORD,I,0,AA-0003018,Y
2,AA-0003018,NaN,M,A,PRMPY,NaN,2005-08-08 00:00:00,NaN,2026-04-01 00:00:00,245.76,...,0,0,1,0,NaN,ORD,I,0,AA-0003018,Y
3,AA-0005897,NaN,M,A,PRMPY,NaN,2000-11-01 00:00:00,NaN,2026-05-01 00:00:00,278.4,...,0,0,1,0,NaN,ORD,I,0,AA-0005897,Y
4,AA-0005897,NaN,M,A,PRMPY,NaN,2000-11-01 00:00:00,NaN,2026-05-01 00:00:00,278.4,...,0,0,1,0,NaN,ORD,I,0,AA-0005897,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107360,PD-0351823,NaN,Q,A,PRMPY,NaN,1990-01-08 00:00:00,NaN,2026-05-15 00:00:00,71.16,...,1,0,1,0,Waiver of Premium Disablement age 60 waiver a...,ORD,I,0,PD-0351823,Y
107361,PD-0351824,NaN,Q,A,PRMPY,NaN,1990-01-08 00:00:00,NaN,2026-04-15 00:00:00,71.16,...,1,0,1,0,Waiver of Premium Disablement age 60 waiver a...,ORD,I,0,PD-0351824,Y
107362,PD-0352604,NaN,A,A,PRMPY,NaN,1990-03-05 00:00:00,NaN,2026-05-02 00:00:00,83.04,...,1,0,1,0,Waiver of Premium Disablement age 60 waiver a...,ORD,I,0,PD-0352604,Y
107363,PD-0345315,NaN,A,A,PRMPY,NaN,1988-06-06 00:00:00,NaN,2026-04-22 00:00:00,19.8,...,1,0,1,0,Waiver of Premium Disablement age 60 waiver a...,ORD,I,0,PD-0345315,Y
107364,PD-0338826,NaN,Q,A,PRMPY,NaN,1986-11-24 00:00:00,NaN,2026-06-18 00:00:00,19.8,...,1,0,1,0,Waiver of Premium Disablement age 60 waiver a...,ORD,I,0,PD-0338826,Y

In [15]:
seriatim.wrvrptcd1.unique()

array([nan, 'LIFE', 'ADB', 'ACCH', 'WP'], dtype=object)

In [16]:
pmdmode_map.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 1 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   pmdmode  6 non-null      object
dtypes: object(1)
memory usage: 176.0+ bytes

In [17]:
seriatim['pmdmode_adjusted'] = seriatim['pmdmode'].apply(map_pmdmode)

In [18]:
seriatim['pmdstsexdt_adjusted'] = np.where(seriatim['pmdstssub'] == 'ETI', seriatim['pmdstsexdt'], None)

In [19]:
columns =['policyno', 'amtpolicy' ,'pbfrsvcd0', 'prmannl', 'pmdissuedt', 'pmddtdwd', 'pmdplan', 'pmdplanver', 'pbfrplan', 'pbfrplanvr', 'pmddebit', 'pmdsts','pmdstssub', 'pmdstsexdt', 
          'pbfamt', 'wrvpbfdtcd', 'wrvpbfdt', 'wrvage', 'wrvduratn', 'wrvrsvfact', 'wrvfacbase', 'wrvscaleby', 'wrvprmuneg', 'wrvprmdefg', 'wrvprmdueg', 'wrvprmadvg', 'wrvprmdefn', 'wrvprmduen', 'wrvgrpind',
         'wrvclass', 'wrvpbfsex', 'pmdmode_adjusted', 'valcode', 'wrvrptcd1', 'wrvrsvamt']

In [20]:
# Ensure the columns exist in the seriatim DataFrame before filtering
missing_columns = [col for col in columns if col not in seriatim.columns]
if missing_columns:
    print(f"Warning: The following columns are missing in the DataFrame: {missing_columns}")

# Filter the DataFrame to include only the specified columns
seriatim_subset = seriatim[columns]

In [21]:
seriatim_subset

,policyno,amtpolicy,pbfrsvcd0,prmannl,pmdissuedt,pmddtdwd,pmdplan,pmdplanver,pbfrplan,pbfrplanvr,...,wrvprmadvg,wrvprmdefn,wrvprmduen,wrvgrpind,wrvclass,wrvpbfsex,pmdmode_adjusted,valcode,wrvrptcd1,wrvrsvamt
0,AA-0002837,1,00922,0,2000-05-01 00:00:00,2026-05-01 00:00:00,9,3,NaN,NaN,...,0,0,0,I,ORD,F,4,00922,NaN,0
1,AA-0003018,5,0920W,0,2000-06-01 00:00:00,2026-04-01 00:00:00,17,3,NaN,NaN,...,0,0,0,I,ORD,F,9,0920W,NaN,0
2,AA-0003018,6,0920W,0,2005-08-08 00:00:00,2026-04-01 00:00:00,17,3,NaN,NaN,...,0,0,0,I,ORD,F,9,0920W,NaN,0
3,AA-0005897,2,00922,13.2,2000-11-01 00:00:00,2026-05-01 00:00:00,9,3,NaN,NaN,...,0,0,0,I,ORD,F,9,00922,NaN,0
4,AA-0005897,3,00922,0,2000-11-01 00:00:00,2026-05-01 00:00:00,9,3,NaN,NaN,...,0,0,0,I,ORD,F,9,00922,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107360,PD-0351823,1,PWP60,0,1990-01-08 00:00:00,2026-05-15 00:00:00,33,P006,NaN,NaN,...,0,0,0,I,ORD,M,4,PWP60,WP,0
107361,PD-0351824,1,PWP60,0,1990-01-08 00:00:00,2026-04-15 00:00:00,33,P006,NaN,NaN,...,0,0,0,I,ORD,M,4,PWP60,WP,0
107362,PD-0352604,1,PWP60,0,1990-03-05 00:00:00,2026-05-02 00:00:00,33,P006,NaN,NaN,...,0,0,0,I,ORD,M,1,PWP60,WP,0
107363,PD-0345315,1,PWP60,0,1988-06-06 00:00:00,2026-04-22 00:00:00,33,P005,NaN,NaN,...,0,0,0,I,ORD,M,1,PWP60,WP,0
107364,PD-0338826,1,PWP60,0,1986-11-24 00:00:00,2026-06-18 00:00:00,33,P005,NaN,NaN,...,0,0,0,I,ORD,M,4,PWP60,WP,0

In [22]:
seriatim_subset.loc[:, 'rectype'] = 'R'
seriatim_subset.loc[:, 'acctno'] = '0'
seriatim_subset.loc[:, 'seealso'] = ''
seriatim_subset.loc[:, 'aaprm'] = ''
seriatim_subset.loc[:, 'aaperiods'] =''
seriatim_subset.loc[:, 'aaamt'] =''
seriatim_subset.loc[:, 'catfstren'] =''
seriatim_subset.loc[:, 'pmdsts'] ='A'
#Next instert catMK table to map the CATMKT

C:\Users\achoijin\AppData\Local\Temp\ipykernel_7012\689148335.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seriatim_subset.loc[:, 'rectype'] = 'R'
C:\Users\achoijin\AppData\Local\Temp\ipykernel_7012\689148335.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seriatim_subset.loc[:, 'acctno'] = '0'
C:\Users\achoijin\AppData\Local\Temp\ipykernel_7012\689148335.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seriatim_subset.loc[:, 'seealso'] = ''
C:\Users\achoijin\AppData\Local\Temp\ipykernel_7012\689148335.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seriatim_subset.loc[:, 'aaprm'] = ''
C:\Users\achoijin\AppData\Local\Temp\ipykernel_7012\689148335.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seriatim_subset.loc[:, 'aaperiods'] =''
C:\Users\achoijin\AppData\Local\Temp\ipykernel_7012\689148335.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seriatim_subset.loc[:, 'aaamt'] =''
C:\Users\achoijin\AppData\Local\Temp\ipykernel_7012\689148335.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seriatim_subset.loc[:, 'catfstren'] =''
C:\Users\achoijin\AppData\Local\Temp\ipykernel_7012\689148335.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seriatim_subset.loc[:, 'pmdsts'] ='A'

In [23]:
seriatim_subset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 107365 entries, 0 to 107364
Data columns (total 42 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   policyno          107365 non-null  object
 1   amtpolicy         107365 non-null  object
 2   pbfrsvcd0         107365 non-null  object
 3   prmannl           107365 non-null  object
 4   pmdissuedt        107365 non-null  object
 5   pmddtdwd          107365 non-null  object
 6   pmdplan           107365 non-null  object
 7   pmdplanver        107365 non-null  object
 8   pbfrplan          0 non-null       object
 9   pbfrplanvr        0 non-null       object
 10  pmddebit          0 non-null       object
 11  pmdsts            107365 non-null  object
 12  pmdstssub         107365 non-null  object
 13  pmdstsexdt        6171 non-null    object
 14  pbfamt            107365 non-null  object
 15  wrvpbfdtcd        103775 non-null  object
 16  wrvpbfdt          107365 non-null  object
 17  wrvage            101863 non-null  object
 18  wrvduratn         101863 non-null  object
 19  wrvrsvfact        107365 non-null  object
 20  wrvfacbase        107365 non-null  object
 21  wrvscaleby        107365 non-null  object
 22  wrvprmuneg        107365 non-null  object
 23  wrvprmdefg        107365 non-null  object
 24  wrvprmdueg        107365 non-null  object
 25  wrvprmadvg        107365 non-null  object
 26  wrvprmdefn        107365 non-null  object
 27  wrvprmduen        107365 non-null  object
 28  wrvgrpind         107365 non-null  object
 29  wrvclass          107365 non-null  object
 30  wrvpbfsex         107365 non-null  object
 31  pmdmode_adjusted  107365 non-null  object
 32  valcode           107365 non-null  object
 33  wrvrptcd1         101803 non-null  object
 34  wrvrsvamt         107365 non-null  object
 35  rectype           107365 non-null  object
 36  acctno            107365 non-null  object
 37  seealso           107365 non-null  object
 38  aaprm             107365 non-null  object
 39  aaperiods         107365 non-null  object
 40  aaamt             107365 non-null  object
 41  catfstren         107365 non-null  object
dtypes: object(42)
memory usage: 34.4+ MB

In [24]:
seriatim_subset.rename(columns = {'wrvgrpind' : 'catindgrp', 'wrvclass' : 'catclass', 'wrvrsvamt' : 'amtreserve'}, inplace=True)

C:\Users\achoijin\AppData\Local\Temp\ipykernel_7012\1353115525.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seriatim_subset.rename(columns = {'wrvgrpind' : 'catindgrp', 'wrvclass' : 'catclass', 'wrvrsvamt' : 'amtreserve'}, inplace=True)

In [25]:
seriatim_subset

,policyno,amtpolicy,pbfrsvcd0,prmannl,pmdissuedt,pmddtdwd,pmdplan,pmdplanver,pbfrplan,pbfrplanvr,...,valcode,wrvrptcd1,amtreserve,rectype,acctno,seealso,aaprm,aaperiods,aaamt,catfstren
0,AA-0002837,1,00922,0,2000-05-01 00:00:00,2026-05-01 00:00:00,9,3,NaN,NaN,...,00922,NaN,0,R,0,,,,,
1,AA-0003018,5,0920W,0,2000-06-01 00:00:00,2026-04-01 00:00:00,17,3,NaN,NaN,...,0920W,NaN,0,R,0,,,,,
2,AA-0003018,6,0920W,0,2005-08-08 00:00:00,2026-04-01 00:00:00,17,3,NaN,NaN,...,0920W,NaN,0,R,0,,,,,
3,AA-0005897,2,00922,13.2,2000-11-01 00:00:00,2026-05-01 00:00:00,9,3,NaN,NaN,...,00922,NaN,0,R,0,,,,,
4,AA-0005897,3,00922,0,2000-11-01 00:00:00,2026-05-01 00:00:00,9,3,NaN,NaN,...,00922,NaN,0,R,0,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107360,PD-0351823,1,PWP60,0,1990-01-08 00:00:00,2026-05-15 00:00:00,33,P006,NaN,NaN,...,PWP60,WP,0,R,0,,,,,
107361,PD-0351824,1,PWP60,0,1990-01-08 00:00:00,2026-04-15 00:00:00,33,P006,NaN,NaN,...,PWP60,WP,0,R,0,,,,,
107362,PD-0352604,1,PWP60,0,1990-03-05 00:00:00,2026-05-02 00:00:00,33,P006,NaN,NaN,...,PWP60,WP,0,R,0,,,,,
107363,PD-0345315,1,PWP60,0,1988-06-06 00:00:00,2026-04-22 00:00:00,33,P005,NaN,NaN,...,PWP60,WP,0,R,0,,,,,
107364,PD-0338826,1,PWP60,0,1986-11-24 00:00:00,2026-06-18 00:00:00,33,P005,NaN,NaN,...,PWP60,WP,0,R,0,,,,,

In [26]:
seriatim_subset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 107365 entries, 0 to 107364
Data columns (total 42 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   policyno          107365 non-null  object
 1   amtpolicy         107365 non-null  object
 2   pbfrsvcd0         107365 non-null  object
 3   prmannl           107365 non-null  object
 4   pmdissuedt        107365 non-null  object
 5   pmddtdwd          107365 non-null  object
 6   pmdplan           107365 non-null  object
 7   pmdplanver        107365 non-null  object
 8   pbfrplan          0 non-null       object
 9   pbfrplanvr        0 non-null       object
 10  pmddebit          0 non-null       object
 11  pmdsts            107365 non-null  object
 12  pmdstssub         107365 non-null  object
 13  pmdstsexdt        6171 non-null    object
 14  pbfamt            107365 non-null  object
 15  wrvpbfdtcd        103775 non-null  object
 16  wrvpbfdt          107365 non-null  object
 17  wrvage            101863 non-null  object
 18  wrvduratn         101863 non-null  object
 19  wrvrsvfact        107365 non-null  object
 20  wrvfacbase        107365 non-null  object
 21  wrvscaleby        107365 non-null  object
 22  wrvprmuneg        107365 non-null  object
 23  wrvprmdefg        107365 non-null  object
 24  wrvprmdueg        107365 non-null  object
 25  wrvprmadvg        107365 non-null  object
 26  wrvprmdefn        107365 non-null  object
 27  wrvprmduen        107365 non-null  object
 28  catindgrp         107365 non-null  object
 29  catclass          107365 non-null  object
 30  wrvpbfsex         107365 non-null  object
 31  pmdmode_adjusted  107365 non-null  object
 32  valcode           107365 non-null  object
 33  wrvrptcd1         101803 non-null  object
 34  amtreserve        107365 non-null  object
 35  rectype           107365 non-null  object
 36  acctno            107365 non-null  object
 37  seealso           107365 non-null  object
 38  aaprm             107365 non-null  object
 39  aaperiods         107365 non-null  object
 40  aaamt             107365 non-null  object
 41  catfstren         107365 non-null  object
dtypes: object(42)
memory usage: 34.4+ MB

In [27]:
def fix_invalid_date(date_str):
    try:
        # Attempt to parse the date
        return pd.to_datetime(date_str, format='%m/%d/%Y', errors='coerce')
    except ValueError:
        # Handle cases with unexpected formats or invalid dates
        try:
            # Extract the date part if a time component is included
            date_part = date_str.split()[0]  # Get only the date
            month, day, year = map(int, date_part.split('/'))
            
            # Check for invalid February 29 in non-leap years
            if month == 2 and day == 29 and is_not_leap_year(year):
                return pd.Timestamp(f'{year}-02-28')
            else:
                raise  # Unexpected case
        except Exception:
            raise ValueError(f"Unable to parse date: {date_str}")

In [28]:
def is_not_leap_year(year):
    return year % 4 != 0 or (year % 100 == 0 and year % 400 != 0)

In [29]:
seriatim_subset['wrvpbfdt'] = seriatim_subset['wrvpbfdt'].apply(fix_invalid_date)

C:\Users\achoijin\AppData\Local\Temp\ipykernel_7012\2758828523.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seriatim_subset['wrvpbfdt'] = seriatim_subset['wrvpbfdt'].apply(fix_invalid_date)

In [30]:
seriatim_subset[seriatim_subset['policyno']=='PD-0032499']

,policyno,amtpolicy,pbfrsvcd0,prmannl,pmdissuedt,pmddtdwd,pmdplan,pmdplanver,pbfrplan,pbfrplanvr,...,valcode,wrvrptcd1,amtreserve,rectype,acctno,seealso,aaprm,aaperiods,aaamt,catfstren
102771,PD-0032499,0,P0395,0,1958-02-10 00:00:00,1958-02-10 00:00:00,33,P001,NaN,NaN,...,P0395,LIFE,193.6825,R,0,,,,,

In [31]:
seriatim_subset.loc[
    seriatim_subset["policyno"] == "PD-0056023",
    "pmddtdwd"
] = pd.Timestamp("1960-02-01")

seriatim_subset.loc[
    seriatim_subset["policyno"] == "PD-0032499",
    "pbfdt"
] = pd.Timestamp("2042-02-10")
seriatim_subset.loc[
    seriatim_subset["policyno"] == "PD-0032499",
    "wrvpbfdt"
] = pd.Timestamp("2042-02-10")

C:\Users\achoijin\AppData\Local\Temp\ipykernel_7012\683398887.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seriatim_subset.loc[

In [34]:
seriatim_subset = seriatim_subset.dropna(subset=['wrvage'], axis=0)

In [35]:
seriatim_subset = seriatim_subset.astype({"amtreserve" : "float64","prmannl" : "float64", "pmdissuedt" : "datetime64[ns]","pmddtdwd" : "datetime64[ns]", "pmdstsexdt" : "datetime64[ns]",
                                          "pbfamt": "float64", "wrvage" : "int64","wrvrsvfact" : "float64", "wrvfacbase" : "float64","wrvscaleby" : "float64", "wrvprmuneg" : "float64",
                                         "wrvprmdefg" : "float64", "wrvprmdueg" : "float64", "wrvprmadvg" : "float64","wrvprmdefn" : "float64","wrvprmduen" : "float64", "wrvpbfdt" : "datetime64[ns]", 
                                          "acctno" :"string", "amtpolicy" : "string", "wrvduratn" : "string", "pmdmode_adjusted" :"string"})

In [36]:
for col, dtype in {
    "amtreserve": "float64","prmannl": "float64","pmdissuedt": "datetime64[ns]",
    "pmddtdwd": "datetime64[ns]", "pmdstsexdt": "datetime64[ns]", "pbfamt": "float64",
    "wrvage": "int64","wrvrsvfact": "float64","wrvfacbase": "float64","wrvscaleby": "float64",
    "wrvprmuneg": "float64","wrvprmdefg": "float64","wrvprmdueg": "float64","wrvprmadvg": "float64",
    "wrvprmdefn": "float64","wrvprmduen": "float64","wrvpbfdt": "datetime64[ns]",
    "acctno": "string","amtpolicy": "string","wrvduratn": "string","pmdmode_adjusted": "string"
}.items():
    try:
        seriatim_subset[col].astype(dtype)
    except Exception as e:
        print(f"❌ Column '{col}' failed: {e}")

In [37]:
mask_invalid = pd.to_datetime(seriatim_subset["pmdissuedt"], errors='coerce').isna() & seriatim_subset["pmdissuedt"].notna()
seriatim_subset.loc[mask_invalid, "pmdissuedt"]

Series([], Name: pmdissuedt, dtype: datetime64[ns])

In [38]:
columns_to_check = ["pmdissuedt", "pmddtdwd", "pmdstsexdt", "wrvpbfdt"]

In [39]:
for col in columns_to_check:
    try:
        pd.to_datetime(seriatim_subset[col])
        print(f"✅ {col} converted successfully.")
    except Exception as e:
        print(f"❌ {col} failed with error: {e}")

✅ pmdissuedt converted successfully.
✅ pmddtdwd converted successfully.
✅ pmdstsexdt converted successfully.
✅ wrvpbfdt converted successfully.

In [40]:
seriatim_subset = seriatim_subset.drop(['pbfrsvcd0', 'pbfdt'],errors="ignore", axis=1)

In [41]:
seriatim_subset.rename(columns={"pmdmode_adjusted": "pmdmode", "wrvrptcd1":"catrsvexh5"}, inplace=True)

In [42]:
seriatim_subset['set_month'] = "202603"

In [44]:
seriatim_subset.to_gbq("converge-database.life_prod.seriatim",
                  if_exists='append',
                  project_id="converge-database")

100%|██████████| 1/1 [00:00<?, ?it/s]

In [43]:
seriatim_subset

,policyno,amtpolicy,prmannl,pmdissuedt,pmddtdwd,pmdplan,pmdplanver,pbfrplan,pbfrplanvr,pmddebit,...,catrsvexh5,amtreserve,rectype,acctno,seealso,aaprm,aaperiods,aaamt,catfstren,set_month
5502,AH-4253105,0,0.00,1948-08-09,1949-01-03,175,1,NaN,NaN,NaN,...,LIFE,21.375,R,0,,,,,,202603
5503,AH-4261794,0,5.28,1949-01-10,1949-01-03,120,1,NaN,NaN,NaN,...,LIFE,25.650,R,0,,,,,,202603
5504,AH-4272995,0,0.00,1949-06-27,1949-01-03,175,1,NaN,NaN,NaN,...,LIFE,38.115,R,0,,,,,,202603
5505,AH-4275247,0,0.00,1949-08-08,1949-01-03,175,1,NaN,NaN,NaN,...,LIFE,30.780,R,0,,,,,,202603
5506,AH-4278589,0,10.44,1949-10-17,2049-10-17,120,1,NaN,NaN,NaN,...,LIFE,423.500,R,0,,,,,,202603
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107360,PD-0351823,1,0.00,1990-01-08,2026-05-15,33,P006,NaN,NaN,NaN,...,WP,0.000,R,0,,,,,,202603
107361,PD-0351824,1,0.00,1990-01-08,2026-04-15,33,P006,NaN,NaN,NaN,...,WP,0.000,R,0,,,,,,202603
107362,PD-0352604,1,0.00,1990-03-05,2026-05-02,33,P006,NaN,NaN,NaN,...,WP,0.000,R,0,,,,,,202603
107363,PD-0345315,1,0.00,1988-06-06,2026-04-22,33,P005,NaN,NaN,NaN,...,WP,0.000,R,0,,,,,,202603
107364,PD-0338826,1,0.00,1986-11-24,2026-06-18,33,P005,NaN,NaN,NaN,...,WP,0.000,R,0,,,,,,202603

In [45]:
seriatim_subset.wrvpbfdtcd.unique()

array(['P', 'M', 'E', ' ', nan], dtype=object)

In [47]:
set_month='202603'

In [48]:
catmkt_query = f'''
UPDATE `life_prod.seriatim` s
SET s.catmkt = (SELECT MAX(product) from `lifetemp.valcode_map` v WHERE LPAD(v.pbfrsvcd1, 5, '0') = LPAD(valcode, 5, '0'))
WHERE set_month='{set_month}'
'''

In [49]:
CREDS = '../../converge-database-0331482f2ee5.json'
client = bigquery.Client.from_service_account_json(json_credentials_path=CREDS)
result = client.query(catmkt_query)

In [50]:
exhibit_query = f'''
UPDATE `life_prod.seriatim` s
SET exhibit5 = (select MAX(exhibit) from `lifetemp.valcode` where LPAD(CAST(s.valcode AS STRING), 5, '0') =valcode_new)
WHERE set_month = "{set_month}"
'''

In [51]:
result = client.query(exhibit_query)

In [52]:
pbrfplan_query = f'''
UPDATE `converge-database.life_prod.seriatim`
SET pbfrplan = 
    CASE 
        WHEN pmdplan IN ('19','40', '41', '42', '43', '44', '95') THEN pmdplan
    END
WHERE set_month = '{set_month}';
'''

In [53]:
result = client.query(pbrfplan_query)

In [54]:
rsv_query = f'''
    UPDATE `converge-database.life_prod.seriatim` AS s
SET s.final_rsv = a.rsvamt
FROM `lifetemp.annuity` AS a
WHERE s.policyno = a.policyno
AND s.set_month = a.set_month
AND s.set_month = '{set_month}';
'''

final_rsv_query = f'''

UPDATE `converge-database.life_prod.seriatim` AS s
SET s.final_rsv = s.amtreserve
WHERE s.final_rsv IS NULL
AND s.set_month = '{set_month}';
'''

In [55]:
famt_query = f'''
UPDATE `converge-database.life_prod.seriatim` AS s
SET s.final_famt = a.total2
FROM `lifetemp.annuity` AS a
WHERE s.policyno = a.policyno
AND s.set_month = a.set_month
AND s.set_month = '{set_month}';
'''

final_famt_query = f'''

UPDATE `converge-database.life_prod.seriatim` AS s
SET s.final_famt = s.pbfamt
WHERE s.final_famt IS NULL
AND s.set_month = '{set_month}';
'''

In [56]:
switch_rsv =f'''
UPDATE `life_prod.seriatim`
set amtreserve = final_rsv
WHERE set_month ='{set_month}'
'''
switch_fmat =f'''
UPDATE `life_prod.seriatim`
set pbfamt = final_famt
WHERE set_month ='{set_month}'
'''

In [57]:
#put a timer on this query
result = client.query(rsv_query)

In [58]:
result = client.query(final_rsv_query)

In [59]:
result = client.query(famt_query)

In [60]:
result = client.query(final_famt_query)

In [61]:
result = client.query(switch_rsv)

In [62]:
result = client.query(switch_fmat)

In [63]:
#If need to export to excel current process is exporting from GBQ

seriatim_subset.to_excel('LIFE_transform_'+set_month+'.xlsx', index=False)